// App notifications - a lightweight, per-user activity feed.
//
// Notifications are generated by store actions (an admin approves your request, a
// club you follow posts an event, you get promoted off a waitlist, an event you
// RSVP'd to moves) and persisted with the rest of the state. Each notification
// names its recipient by `userId`; the UI selects the ones for the effective user.

export type NotificationKind =
  | 'autoAccepted'
  | 'applicationApproved'
  | 'applicationDenied'
  | 'membershipApproved'
  | 'newEventFromFollowed'
  | 'eventUpdated'
  | 'promotedFromWaitlist'
  | 'joinedWaitlist'

export interface AppNotification {
  id: string
  userId: string // recipient
  kind: NotificationKind
  title: string
  body: string
  eventId?: string
  clubId?: string
  ts: number // epoch ms
  read: boolean
}

/** Where clicking a notification should take you. */
export function notificationHref(n: AppNotification): string | null {
  if (n.eventId) return `/event/${n.eventId}`
  if (n.clubId) return `/club/${n.clubId}`
  return null
}

/** Coarse accent per kind so the panel can tint icons consistently. */
export function notificationAccent(kind: NotificationKind): 'success' | 'pink' | 'muted' {
  switch (kind) {
    case 'autoAccepted':
    case 'applicationApproved':
    case 'membershipApproved':
    case 'promotedFromWaitlist':
      return 'success'
    case 'newEventFromFollowed':
    case 'eventUpdated':
      return 'pink'
    default:
      return 'muted'
  }
}

/** "just now" / "3m" / "2h" / "4d" / "Aug 3" from a timestamp. */
export function relativeTime(ts: number, now: number = Date.now()): string {
  const diff = Math.max(0, now - ts)
  const min = Math.floor(diff / 60_000)
  if (min < 1) return 'just now'
  if (min < 60) return `${min}m`
  const hr = Math.floor(min / 60)
  if (hr < 24) return `${hr}h`
  const day = Math.floor(hr / 24)
  if (day < 7) return `${day}d`
  return new Date(ts).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}
